# Permission to use /chatcolor reload - to reload the config
reload-permission: "is.op"

# Permission to use the /chatcolor - command to view the gui
# Leave as "none" if no permission needed
chatcolor-permission: "chatcolor.use"

# Title of the chat color gui, supports hex colors, you can find a generator here https://minecraft.menu/minecraft-rgb-generator - Make sure you're on Legacy mode.
chatcolor-gui-title: "&x&0&b&e&5&f&bChat Color Selector"

# Sections for each of the color options, names are specific, values are not
# Set the permission to "none" if you want no permission required
# The valid item types are available here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# The item-name, item-lore, & no-permission-message supports hex colors, Check out this to generate them, https://minecraft.menu/minecraft-rgb-generator
sections:
  red:
    item-type: "DIRT"
    item-name: "NAME"
    item-lore: "LORE"
    no-permission-message: "Sorry, you don't have xyz to do this."
    permission: "none"
    color-hex-option-1: "#deb440"
    color-hex-option-2: "#deb440"
    color-hex-option-3: "#deb440"
    color-hex-option-4: "#deb440"
    color-hex-option-5: "#deb440"
    color-hex-option-6: "#deb440"
    color-hex-option-7: "#deb440"
  yellow:
    item-type: "DIRT"
    item-name: "NAME"
    item-lore: "LORE"
    no-permission-message: "Sorry, you don't have xyz to do this."
    permission: "use.color"
    color-hex-option-1: "#deb440"
    color-hex-option-2: "#deb440"
    color-hex-option-3: "#deb440"
    color-hex-option-4: "#deb440"
    color-hex-option-5: "#deb440"
    color-hex-option-6: "#deb440"
    color-hex-option-7: "#deb440"
  green:
    item-type: "DIRT"
    item-name: "NAME"
    item-lore: "LORE"
    no-permission-message: "Sorry, you don't have xyz to do this."
    permission: "use.color"
    color-hex-option-1: "#deb440"
    color-hex-option-2: "#deb440"
    color-hex-option-3: "#deb440"
    color-hex-option-4: "#deb440"
    color-hex-option-5: "#deb440"
    color-hex-option-6: "#deb440"
    color-hex-option-7: "#deb440"
  teal:
    item-type: "DIRT"
    item-name: "NAME"
    item-lore: "LORE"
    no-permission-message: "Sorry, you don't have xyz to do this."
    permission: "use.color"
    color-hex-option-1: "#deb440"
    color-hex-option-2: "#deb440"
    color-hex-option-3: "#deb440"
    color-hex-option-4: "#deb440"
    color-hex-option-5: "#deb440"
    color-hex-option-6: "#deb440"
    color-hex-option-7: "#deb440"
  blue:
    item-type: "DIRT"
    item-name: "NAME"
    item-lore: "LORE"
    no-permission-message: "Sorry, you don't have xyz to do this."
    permission: "use.color"
    color-hex-option-1: "#deb440"
    color-hex-option-2: "#deb440"
    color-hex-option-3: "#deb440"
    color-hex-option-4: "#deb440"
    color-hex-option-5: "#deb440"
    color-hex-option-6: "#deb440"
    color-hex-option-7: "#deb440"
  purple:
    item-type: "DIRT"
    item-name: "NAME"
    item-lore: "LORE"
    no-permission-message: "Sorry, you don't have xyz to do this."
    permission: "use.color"
    color-hex-option-1: "#deb440"
    color-hex-option-2: "#deb440"
    color-hex-option-3: "#deb440"
    color-hex-option-4: "#deb440"
    color-hex-option-5: "#deb440"
    color-hex-option-6: "#deb440"
    color-hex-option-7: "#deb440"
  white:
    item-type: "DIRT"
    item-name: "NAME"
    item-lore: "LORE"
    no-permission-message: "Sorry, you don't have xyz to do this."
    permission: "use.color"
    color-hex-option-1: "#deb440"
    color-hex-option-2: "#deb440"
    color-hex-option-3: "#deb440"
    color-hex-option-4: "#deb440"
    color-hex-option-5: "#deb440"
    color-hex-option-6: "#deb440"
    color-hex-option-7: "#deb440"